web/api/urls.py
from django.urls import path
from .views import test_get_api, test_post_api


urlpatterns = [
    path("test-get-api/", test_get_api),
    path("test-post-api/", test_post_api),
]

web/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('frontend/', include("frontend.urls")),
]

web/frontend/urls.py
from django.urls import path
from .views import Index, IndexCopy

app_name = "frontend"

urlpatterns = [
    path('', Index, name="index"),
    path('copy', IndexCopy, name="index_copy"),
]

web/aws_test/models.py
from django.db import models


class Person(models.Model):
    id = models.BigIntegerField(primary_key=True)
    birthday = models.DateField(null=False)

web/api/views.py
from django.shortcuts import render
import subprocess


def test_get_api(request):
    subprocess.Popen(["python", "manage.py", "get_api", "1", "2", "3", "4"])
    return render(request, "api/test.html")

def test_post_api(request):
    subprocess.Popen(["python", "manage.py", "post_api", "1", "2", "3", "4"])
    return render(request, "api/test.html")

web/aws_test/views.py
from django.shortcuts import render

# Create your views here.

web/frontend/views.py
from django.shortcuts import render

def Index(request):
    return render(request, "frontend/index.html")

def IndexCopy(request):
    return render(request, "frontend/index_copy.html")

    

web/templates/api/test.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
</head>
<body>
    <h1>Succeess!</h1>
</body>
</html>

web/templates/frontend/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static 'css/frontend/index.css' %}>
    <title>test</title>
</head>
<body>
    <div class="index1">
        {% include "selectbox.html" %}
    </div>
    <a href="{% url 'frontend:index_copy' %}">コピーへ</a>
</body>
</html>

web/templates/frontend/index_copy.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static 'css/frontend/index_copy.css' %}>
    <title>test</title>
</head>
<body>
    <div class="index1">
        {% include "selectbox.html" %}
    </div>
    <a href="{% url 'frontend:index' %}">Indexへ</a>
</body>
</html>

web/templates/selectbox.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
<div class="select-container">
</div>